### ISSUE TITLE
get_server_clients_detailed() NoneType

### ISSUE THREAD

**Issue by kforbro** [mick88/samp-client#19]
Error when online above 100

`from samp_client.client import SampClient

with SampClient(address='145.239.16.20', port=7777) as client:
    clients = client.get_server_clients_detailed()`

`Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/radmirvkbot/probe.py", line 4, in <module>
    clients = client.get_server_clients_detailed()
  File "C:\Users\User\PycharmProjects\radmirbot\venv\lib\site-packages\samp_client\client.py", line 122, in get_server_clients_detailed
    num_clients = decode_int(response[:2])
TypeError: 'NoneType' object is not subscriptable`

**Comment by mick88** [comment]
Which version of library are you using?
