### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DeViL252** [mick88/samp-client#26]
If you use directly like this-
`with SampClient(address='localhost', port=7777) as client:
    print(client.get_server_info())`
getting this NoneType  object errors
```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    print(client.get_server_info())
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/samp_client/client.py", line 65, in get_server_info
    hostname = decode_string(response, 5, 4)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/samp_client/utils.py", line 56, in decode_string
    length = decode_int(string[len_pos:len_end])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by mick88** [comment]
Cannot replicate in latest version 3.0.1

```
In [1]: from samp_client.client import SampClient

In [2]: with SampClient(address='server.convoytrucking.net', port=7777) as client:
   ...:     print(client.get_server_info())
   ...:
ServerInfo(password=False, players=6, max_players=100, hostname='Convoy Trucking', gamemode='Convoy Trucking 3.6.3', language='English')
```
